# kuppanmandal@gmail.com

# Machine Learning concepts on Python: 
<h3> without using numpy or sklearn or other third party packages </h3>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [1]:
# In this code matrix multiplication is performed without 
# using third party libraries
# martix_mul function performs matrix multiplication on
# sum of rows with columns of each element
def matrix_mul(A, B):
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result
# to get size of the matrix
A_row = int(input("Enter A matrix row :"))
A_column = int(input("Enter A matrix column :"))
B_row = int(input("Enter B matrix row :"))
B_column = int(input("Enter B matrix column :"))
# decision making to perform matrix multiplication
if A_column == B_row: # or use "len(A[0]) == len(B)""
    result = [[0 for i in range(B_column)] for j in range(A_row)] #len(B[0]) & len(A)
    print("Enter A matrix elements in row sequence")
    A = [[int(input()) for i in range(A_column)] for j in range(A_row)]
    print("Enter B matrix elements in row sequence")
    B = [[int(input()) for i in range(B_column)] for j in range(B_row)]
    print("The result of matrix multiplication\n", matrix_mul(A, B))
else:
    print("Matrix multiplication is not possible on unequal A columns and B rows")

Enter A matrix row :2
Enter A matrix column :2
Enter B matrix row :2
Enter B matrix column :5
Enter A matrix elements in row sequence
1
2
3
4
Enter B matrix elements in row sequence
1
2
3
4
5
5
6
7
8
9
The result of matrix multiplication
 [[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [2]:
from random import sample
A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
#A = [1, 2, 3, 4, 5]
A.sort()
number = 100
A_len = len(A)
sum_up = 0
for f in range(1,A_len+1):
    sum_up += f
eq_dis = int((number-sum_up)/A_len)
eq_list = []
for j in range(1,A_len+1):
    eq_list.append(j+eq_dis)
total = 0
for k in eq_list:
    total +=k
balance = 0
if total != number:
    balance = number - total
for i in range(1,balance+1):
    eq_list[-i] = eq_list[-i] + 1
    balance -= 1
weighted_list = []
for l in range(A_len):
    weighted_list += [A[l]]*eq_list[l]
sample_list = sample(weighted_list, k=100)
for i in A:
    print("if f({}) appears max of {} times".format(i,sample_list.count(i)),end=' ')
    if i != max(A):
        print("then")
else:
    print("\n\nIn case appear times reduces of one element, will increase in other")

if f(0) appears max of 5 times then
if f(5) appears max of 6 times then
if f(6) appears max of 7 times then
if f(10) appears max of 8 times then
if f(13) appears max of 9 times then
if f(27) appears max of 11 times then
if f(28) appears max of 12 times then
if f(45) appears max of 13 times then
if f(79) appears max of 14 times then
if f(100) appears max of 15 times 

In case appear times reduces of one element, will increase in other


<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [3]:
import re
# using re package, findall function identify digits
# and convert as # using sub function
def replace_digits(String):
    replaced_hash = ''
    only_digit = re.findall("[0-9]", String)
    for item in only_digit:
        hash_symbol = re.sub("\d", "#", item)
        replaced_hash += hash_symbol
    '''
    # insted of the above code can use like below code without re package
    for char in String:
        if char.isdigit() == True:
            replaced_hash += '#'
    '''
    return replaced_hash

String = input("Enter String to find only digits as #: ")
replace_digits(String)

Enter String to find only digits as #: #2a$#b%c%561#


'####'

<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [4]:
# always rank has been provided based on marks not on number of students
# identify the marks first using display_dash_board function
def display_dash_board(marks):
    marks.sort()
    top_5_students = []
    for i in range(1, 6):
        top_5_students.append(marks[-i])
    least_5_students = []
    for i in range(0, 5):
        least_5_students.append(marks[i])
    students_within_25_and_75 = []
    per_25 = len(marks)*25/100
    per_75 = len(marks)*75/100
# In above list 25th, 75th percentile are 2.5/10 7.5/10
# index starts from 0 on list but percentiles between 1 and 10
    for i in range(1,len(marks)+1):
        if i > per_25 and i < per_75:
            students_within_25_and_75.append(marks[i-1])
    return top_5_students, least_5_students, students_within_25_and_75
# display students name and marks only on criteria
def display(part, students_list):
    print(part)
    for key in students_list:
        print(students_map[key], key)
    print("\n")
    
students=['student1','student2','student3','student4','student5',\
          'student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
# mapping students and marks which obtain from user
students_map = {mark:student for mark, student in zip(marks, students)}

top_5_students, least_5_students, \
students_within_25_and_75 = display_dash_board(marks)
display('a.', top_5_students)
display('b.', least_5_students)
display('c.', students_within_25_and_75)

a.
student8 98
student10 80
student2 78
student5 48
student7 47


b.
student3 12
student4 14
student9 35
student6 43
student1 45


c.
student9 35
student6 43
student1 45
student7 47
student5 48




<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [5]:
import math
# the code find the distance between two points of S and P
# and sort out only the five nearest points
def closest_points_to_p(S, P):
    list_of_all = []
    order_dict = {}
    for i in range(len(S)):
        n = S[i][0]*P[0] + S[i][1]*P[1]
        a = math.sqrt(math.pow(S[i][0],2) + math.pow(S[i][1],2))
        b = math.sqrt(math.pow(P[0],2) + math.pow(P[1],2))
        list_of_all.append(math.acos(n / (a * b)))
        order_dict[list_of_all[i]] = tuple((S[i][0],S[i][1]))
    list_of_all.sort()
    closest_points_to_p = []
    for i in range(5):
        item = list_of_all[i]
        if item in order_dict.keys():
            closest_points_to_p.append(order_dict[item])
    return closest_points_to_p

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
for point in points:
    print(point)

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [6]:
import math
import re
# for each line the points find its distance of positive and negative values
# using Half_space criteria identify color points lies above or below line
def i_am_the_one(red,blue,line):
    l = re.findall(r"[-+]?\d*\.\d+|[-+]?\d+", line)
    l_abc = []
    for i in l:
        l_abc.append(float(i))
    def dist_color(color,l_abc):
        dist_color = []
        for i_c in color:
            d = (l_abc[0] * i_c[0] + l_abc[1] * i_c[1] + l_abc[2]) /\
            (math.sqrt(l_abc[0] * l_abc[0] + l_abc[1] * l_abc[1]))
            dist_color.append(d)
        return dist_color
    red_dist = dist_color(red, l_abc)
    blue_dist = dist_color(blue, l_abc)
    for item in red_dist:
        if item < 0:
            return 'NO'
    for item in blue_dist:
        if item > 0:
            return 'NO' 
    return 'YES'

Red= [(1,1),(2,1),(4,2),(2,4),(-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no)

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [7]:
# using this code to find smoothing value of before and after elements
def curve_smoothing(string):
    if string == None:
        return "Nothing to smooth"
    else:
        string_list = string.split(',')
        index = next_item = last_index = last_item = 0
        for index in range(len(string_list)):
            if string_list[index] != '_' or (index+1 == len(string_list)):
                if string_list[index] == '_':
                    next_item = 0
                else:
                    next_item = int(string_list[index])
                new_item = (next_item + last_item) / (index - last_index + 1)
                for i in range(last_index, index + 1):
                    string_list[i] = int(new_item)
                last_item = new_item
                last_index = index
        return string_list

S=  "_,_,30,_,_,_,50,_,_"
print(curve_smoothing(S))

[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [8]:
# in this code so many conversation made 
# because of eliminate repeatation and sorted form
def compute_conditional_probabilites(A):
    for F_item in sorted(list({item[0] for item in A})):
        for S_item in sorted(list({item[1] for item in A})):
            count = 0
            for i in range(len(A)):
                j=0 # from the statement identified 2 columns on all the time
                if F_item in A[i][j] and S_item in A[i][j+1]:
                    count += 1
            print("P(F={}|S=={})={}/{}".format(F_item, S_item, count, \
                        [item[1] for item in A].count(S_item)), end='  ')
        print("\n", end='')
# input vales always provide in string form, unless it follows data type
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],\
     ['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
compute_conditional_probabilites(A)

P(F=F1|S==S1)=1/4  P(F=F1|S==S2)=1/3  P(F=F1|S==S3)=0/3  
P(F=F2|S==S1)=1/4  P(F=F2|S==S2)=1/3  P(F=F2|S==S3)=1/3  
P(F=F3|S==S1)=0/4  P(F=F3|S==S2)=1/3  P(F=F3|S==S3)=1/3  
P(F=F4|S==S1)=1/4  P(F=F4|S==S2)=0/3  P(F=F4|S==S3)=1/3  
P(F=F5|S==S1)=1/4  P(F=F5|S==S2)=0/3  P(F=F5|S==S3)=0/3  


<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [9]:
# this code performs with list manner of operations has more code
def string_features(S1, S2):
    S1_list = S1.split()
    S2_list = S2.split()
    a = len(common_words(S1_list, S2_list))
    b = differ_in_words(S1_list, S2_list)
    c = differ_in_words(S2_list, S1_list)
    return a, b, c

def common_words(list_1, list_2):
    return [item for item in list_1 if item in list_2]

def differ_in_words(list_1, list_2):
    return [item for item in list_1 if item not in list_2]
'''# instead of above code use set operations which can perform more easier
# but the exact output as same as can execute by above code
def string_features(S1, S2):
    x = set(S1.split())
    y = set(S2.split())
    a = len(x & y)
    b = list(x - y)
    c = list(y - x)
    return a, b, c
'''
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print("a. ",a,"\nb. ",b,"\nc. ", c)

a.  7 
b.  ['first', 'F', '5'] 
c.  ['second', 'S', '3']


<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [10]:
import math
# code done based on the formula to calculate error function
def compute_log_loss(A):
    fun_y = 0
    for i in range(len(A)):
        fun_y += ((A[i][0]) * math.log10(A[i][1]) +\
                  (1-A[i][0]) * math.log10(1-A[i][1]))
    loss = -(fun_y)/len(A)
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print("{0:0.5f}".format(loss))

0.42431


# Conclusion
Form my knowledge, I hope the code will satisfy the criteria. May be at some point, time and space complexity utilize more than as usual 